spring:
  application:
    name: forum
  data:
    redis:
      port: 6379
      password: 123456
      host: localhost
      database: 0

  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_forum?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai

knife4j:
  enable: true
  setting:
    language: zh_cn